### ISSUE TITLE
Bump Python to >= 3.9

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/pyxdf#101]
`pyxdf` seems to support Python >= 3.5, at least based on the badge we're showing in the [`README.md`](https://raw.githubusercontent.com/xdf-modules/pyxdf/main/README.md). I don't think that this is accurate, and in any case I propose to bump the minimum required Python version to 3.9. All versions <= 3.7 are EOL, and support for 3.8 will end soon (see [here](https://devguide.python.org/versions/)). The scientific packages ecosystem has converged on 3.9 as its current minimum Python version, so I think we should do the same. OK with everyone?

(This would allow us to e.g. get rid of the `try`/`except` hoops we're currently jumping through in #100.)

**Comment by cboulay** [comment]
Good with me.
