### ISSUE TITLE
Replace Azure Pipelines with GitHub Actions

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/pyxdf#103]
Our Azure Pipeline workflows have been dysfunctional for some time now. This means that neither tests nor publishing on PyPI works. We should replace this with suitable GitHub Actions and restore automatic publishing whenever a new release is created.

**Comment by cboulay** [comment]
Tests have now been replaced with GHA in #106 .
I think this issue stays open until pypi releases are replaced too. Is that right?

**Comment by cbrnr** [comment]
Yes, correct.
