### ISSUE TITLE
Use uv for project management

### ISSUE THREAD

**Issue by cboulay** [xdf-modules/pyxdf#125]
We should probably upgrade from setup.py to pyproject.toml.

I've been using [uv](https://docs.astral.sh/uv/) to manage all my Python projects recently and I like it much more than poetry.

I will put together a PR to migrate to using uv, including refactoring some folders and CI scripts.

**Comment by cbrnr** [comment]
Same, just note that uv resolves differently than pip, which might sometimes be a problem (see ).
