### ISSUE TITLE
XDF.jl (Julia importer)

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/pyxdf#72]
I know that this is not the best place, but I wanted to let you know that I've written a Julia importer for XDF:

https://github.com/cbrnr/XDF.jl

If you want to give it a try, let me know how you like it and be sure to report any issues and feature requests you might have.

**Comment by tstenner** [comment]
You could open a PR to include it as submodule in the https://github.com/sccn/xdf repository

**Comment by cbrnr** [comment]
Good idea!

**Comment by chkothe** [comment]
@cbrnr do you have any plans to migrate that to xdf-modules at some point? 

If so, I'm wondering whether it incurs any hassle on the end-user side once that submodule is flipped from one upstream repo URL to another... does anyone have experience with that?

**Comment by cboulay** [comment]
I would assume that GitHub redirects work even if it's a submodule. Even if not, as long as we update the submodule pointer within the parent `xdf` repo as soon as the move is made, then it should be transparent to users. The default operations of `git pull && git submodule update` will first update the submodule URL before pulling from the new URL.
