### ISSUE TITLE
Error when dejitter_timestamps=False on stream without samples

### ISSUE THREAD

**Issue by jzerfowski** [xdf-modules/pyxdf#81]
When calling load_xdf(... dejitter_timestamps=False) on a file containing a stream without any samples, an IndexError is thrown in line pyxdf.py:384

`duration = stream.time_stamps[-1] - stream.time_stamps[0]
IndexError: index -1 is out of bounds for axis 0 with size 0`

This is because the first and last element of this empty array are accessed. For that matter, if the stream had only a single sample, duration would be 0 and the next line `stream.effective_srate = len(stream.time_stamps) / duration` would cause a division by 0 error.

This could be fixed by adding a condition
```
# Default effective sampling rate to 0 if stream does not contain any samples
if len(stream.time_stamps) <= 1:
    stream.effective_srate = 0
    break
```
I couldn't manage to open a new pull request, but please let me know if you need further information. I'm using pyxdf==1.16.3 but the error seems to be still in #5384490

**Comment by jzerfowski** [comment]
Upload MWE with 0, 1 and 2 samples to expose the bug
[mwe.zip](https://github.com/xdf-modules/pyxdf/files/7687792/mwe.zip)

**Comment by cbrnr** [comment]
Thanks @jzerfowski! I'd rather not `break` out of the loop though, because that way you ignore any additional streams that also need to be processed. Therefore, I propose the following change (starting at line 383):

```python
        for stream in temp.values():
            if len(stream.time_stamps) > 1:  # requires at least two samples
                duration = stream.time_stamps[-1] - stream.time_stamps[0]
                stream.effective_srate = len(stream.time_stamps) / duration
            else:
                stream.effective_srate = 0
```

I wonder why you could not open a PR - this should work. Can you provide more details? I would like you to implement this change because you found the issue, reported the issue, and proposed a solution, so you should be credited for all of that!

**Comment by agricolab** [comment]
hey, @cbrnr  just had made that same design choice and opened a PR. Only difference was i initialized stream.effective_srate explitivly with a float, i.e `0.0`. 

https://github.com/xdf-modules/pyxdf/pull/82/commits/3c712f241315b04b112109e1e7aea6b5319eab56#diff-ef075678955858b0ccf9c1a819363246f7d68dc5a2aae4320a5f9ab91e164385R384-R388

Feel free to merge if that's ok with you.

**Comment by jzerfowski** [comment]
Hi @cbrnr, the proposed solution by @agricolab looks good to me, merging that PR would be fine for me. You're right that my `break` statement doesn't make sense. I guess this should have been a `continue` instead, but I guess the explicit if/else is more pythonic anyways.

**Comment by cbrnr** [comment]
Alright!

**Comment by jzerfowski** [comment]
@cbrnr 
> I wonder why you could not open a PR - this should work. Can you provide more details? I would like you to implement this change because you found the issue, reported the issue, and proposed a solution, so you should be credited for all of that!

Nevermind, I guess I just didn't look properly. Will open a PR for the next issue I find!
