### ISSUE TITLE
Make progress bar 

### ISSUE THREAD

**Issue by VladimirR46** [xdf-modules/pyxdf#85]
Hello! 
I need to make a progress bar to display the xdf file loading process.
I am using the pyqt5 GUI.

I have now added my function (signal) to the main loop, but I can't accurately calculate the loading percentage from 0-100%.

    with open_xdf(filename) as f:
        # for each chunk
        while True:
            # noinspection PyBroadException
            try:
                # read [NumLengthBytes], [Length]
                chunklen = _read_varlen_int(f)

--->         progress.emit(1) # My function!!!

            except EOFError:
                break
            except Exception:

How can I do this?

**Comment by chkothe** [comment]
You could look at the byte position in the file and divide that by the file size. 

One could theoretically add the byte position to the `on_chunk` callback function as an optional extra argument (if on_chunk can accept it) to enable these kinds of use cases without having to 'hack' the code.
