### ISSUE TITLE
Azure Pipelines broken?

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/pyxdf#90]
It seems like the automatic publishing step doesn't work anymore. I just created a new tag v1.16.4, but the version on PyPI is still 1.16.3. I can't even find evidence that Azure Pipelines was running the job, and I don't seem to have access to its settings either (I was expecting to see this in the "Actions" section here in the GitHub repo).

@cboulay can you check what's going on? And maybe you could also add me to Azure Pipelines so that I can fix it myself next time? That is, if Azure Pipelines run under your personal account, we should probably create a new one for this organization and repo (i.e. `xdf-modules/pyxdf`).

Alternatively, we could also switch to GitHub Actions, which doesn't require any external services.

**Comment by cbrnr** [comment]
If we can't make this work for v1.16.4, it would be great if you could manually make this PyPI release. You could also give me access on PyPI so I can do it myself.

**Comment by cbrnr** [comment]
@chkothe can you make me an owner on PyPI?

**Comment by cboulay** [comment]
@cbrnr you are now an owner.

**Comment by cboulay** [comment]
I just scrolled through my Azure account and couldn't even find the pipelines section, nor if I was part of an organization.

If you're up to it, I encourage you to transition to GitHub Actions. That's a lot more familiar to me.
https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by cbrnr** [comment]
Yes, I'm using GHA in all my other repos. I'll try to switch this repo soon, but it will take some time. Thanks for making me an owner, I will upload v1.16.4 manually. Or do you have time to do it?

**Comment by cbrnr** [comment]
I just published v1.16.4!
